<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiMjosC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiMjosC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBiMjosC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBiMjosC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBiMjosC\appAppKernelProdContainer([
    'container.build_hash' => 'BiMjosC',
    'container.build_id' => '8e8f0805',
    'container.build_time' => 1730654998,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiMjosC');
